import { useContext } from 'react';
import { WalletContext } from '@contexts/walletContext';

export const useWallet = () => {
  const {
    dataPnL,
    connectWallet,
    disableConnectWallet,
    dataOrders,
    dataMarket,
    dataPosition,
    traderFunction,
    dataLadder,
    productsListKey,
    productSelect,
    changeProduct,
    markPrice,
    qtyGlobal,
    setQtyGlobal,
    isConnect,
    productIndex,
    setProductIndex,
    netWorkConnect,
    setNetWorkConnect,
    fundingRateList,
    productList,
    markPriceList,
    setWalletConnect,
    walletConnect,
    indexPriceList,
    accountSelect,
    setAccountSelect,
    cashBalance,
    USDBalance,
    setLoading,
    loading,
    onSelectPrice,
    priceSelect,
  } = useContext(WalletContext);
  return {
    dataPnL,
    connectWallet,
    disableConnectWallet,
    dataOrders,
    dataMarket,
    dataPosition,
    traderFunction,
    dataLadder,
    productsListKey,
    productSelect,
    changeProduct,
    markPrice,
    qtyGlobal,
    setQtyGlobal,
    isConnect,
    setProductIndex,
    productIndex,
    netWorkConnect,
    setNetWorkConnect,
    fundingRateList,
    productList,
    markPriceList,
    setWalletConnect,
    walletConnect,
    indexPriceList,
    accountSelect,
    setAccountSelect,
    cashBalance,
    USDBalance,
    setLoading,
    loading,
    onSelectPrice,
    priceSelect,
  };
};
